name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Version
        id: version
        run: echo "VERSION=${GITHUB_SHA:0:7}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t sudovinh/debravinh:$VERSION .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker Image
        run: |
          docker tag sudovinh/debravinh:$VERSION sudovinh/debravinh:$VERSION
          docker push sudovinh/debravinh:$VERSION

      - name: Update Readme
        run: |
          sed -i "s|Latest Image Version: .*|Latest Image Version: sudovinh/debravinh:$VERSION}|" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "dev+cicd@sudovinh.com"
          git config --local user.name "svc-sudovinh-cicd"
          git add README.md
          git commit -m "Update README with latest version and build status"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
